library(ggplot2)
#Sober Background theme
sb_sober_theme_col <-theme(axis.text.x = element_text(
  family = "Lato",
  size = 10,
  face = "bold"),
  axis.text.y = element_text(family = "Lato",
                             size = 10,
                             face = "bold"),
  panel.background = element_rect(fill = "white"),
  panel.grid.major = element_line(colour= NULL, linetype = NULL),
  axis.title = element_text(family = "Lato",
                            face = "plain"),
  plot.title = element_text(family = "Lato",
                            size = 14,
                            face = "plain"))

sb_sober_theme_line <-theme(axis.text.x = element_text(size = 10,
                                                       face = "bold",
                                                       angle = 30),
                            axis.text.y = element_text(family = "Lato",
                                                       size = 10,
                                                       face = "bold"),
                            panel.background = element_rect(fill = "white"),
                            panel.grid.major = element_line(colour= "black", linetype = 9),
                            axis.title = element_text(family = "Lato",
                                                      face = "plain"),
                            plot.title = element_text(family = "Lato",
                                                      size = 14,
                                                      face = "plain"),
                            legend.title = element_blank(),
                            legend.text = element_text(family = "Lato"),
                            legend.box = "horizontal",
                            legend.box.just = "bottom",
                            legend.position = "bottom")

sb_sober_theme_pie <-theme(axis.text.y = element_text(family = "Lato",
                                                      size = 10,
                                                      face = "bold"),
                           panel.background = element_blank(),
                           panel.grid.major = element_blank(),
                           axis.title = element_blank(),
                           axis.text.x = element_blank(),
                           axis.ticks.y = element_blank(),
                           plot.title = element_text(family = "Lato",
                                                     size = 14,
                                                     face = "plain"),
                           legend.title = element_blank(),
                           legend.text = element_text(family = "Lato",
                                                      size = 14),
                           legend.box = "horizontal",
                           legend.position = "left",
                           legend.direction = "vertical")

sb_sober_theme_text <-theme(plot.title.position = "plot",
                            axis.text = element_blank(),
                            panel.background = element_rect(fill = "white"),
                            panel.grid = element_blank(),
                            axis.title = element_blank(),
                            plot.title = element_text(family = "Lato",
                                                      size = 16,
                                                      face = "bold"),
                            legend.title = element_blank())